# Generated by Django 5.0.2 on 2024-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0004_rename_apropos_experience_formation_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantite_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
