# Generated by Django 5.0.2 on 2024-03-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0005_alter_product_quantite_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='devise_money',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
