# Generated by Django 5.0.2 on 2024-03-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0008_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='etablissement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
